import "./globals.css";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Classroom Management",
  description: "Generated by create-nx-workspace",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
